### ISSUE TITLE
Crash at FUNCTION_SQ_COM.ERB

### ISSUE THREAD

**Issue by SecretU4** [mosochu/EraSQNK#14]
There are no kyobae press at FUNCTION_SQ_COM.ERB 's INSERT case, but EVENT_K37.ERB calls INSERT with kyobae press.
In my opinion, someone(original editor or translator) should make a new case at INSERT,

or change IF sentence at EVENT_K37.ERB.

p.s. kyobae press is a branch command when player try command num 67 (gulgokwii) twice.

original report at [here](https://gall.dcinside.com/mgallery/board/view/?id=textgame&no=37958)

**Comment by SecretU4** [comment]
+ I cannot put label to my article. If someone need to put label, repo's admin should open that function.
    + when I search about label problem, I found only contributors can put label.

**Comment by mosochu** [comment]
fixed with 84a61ef
by excluding insert check
