### ISSUE TITLE
Renovation Branch Error check

### ISSUE THREAD

**Issue by kimbavel** [mosochu/EraSQNK#9]
1. No matching ()
警告Lv2:TRAIN\EVENT_YOBAI.ERB:321行目:字句解析中に対応する')'のない'('を発見しました
			PRINTFORMW 당신은 %CALLNAME:TARGET%에 대한 배반을 느끼면서도, 이윽고 **%(CALLNAME:(TARGET:1)%**의 허리놀림에 응하듯 스스로 허리 흔들기를 시작해 버린다…
2. ARG is not declared (maybe ignored)
警告Lv1:SHOP\ACCESSORY_SYSTEM.ERB:421行目:関数宣言に引数変数"ARG"が使われていない関数中で"ARG"が使われています(関数の引数以外の用途に使うことは推奨されません。代わりに#DIMの使用を検討してください)
		LOCALS = [{ARG, 2}] %PRINT_ACCESSORY_NAME(FLAG:(CHOICE:1))% ＬＶ{FLAG:(CHOICE:1 + 9) + 1, 2}
3. No matching %%
警告Lv2:EVENT_K\EVENT_K22_3.ERB:4053行目:'%'が使われましたが対応する'%'が見つかりません
						PRINTFORMW __을 조르듯 달라붙어오는 _의 움직임에 **(CALLNAME:TARGET,"는")%** 뜨거운 한숨을 몰아쉬며 완만하게 허리를 움직였다
4. No matching %%
警告Lv2:EVENT_K\EVENT_K22_3.ERB:6419行目:'%'が使われましたが対応する'%'が見つかりません
				PRINTFORMW 「삽입할 필요 없어, %CNAME("二人称")는 이것으로 충분하니까」

**Comment by mosochu** [comment]
Please check commits 588a90c, 8421cba, 055536c to fix these issues.
#9-2 issue is affected on master branch too.
